# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setWindowTitle("Calculator")
        self.centralwidget.setWindowIcon(QtGui.QIcon("684ff11278d4517d4a64b6d99e8ce402.png"))
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(110, 220, 320, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.five = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 1, 1, 1, 1)
        self.four = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 1, 0, 1, 1)
        self.eight = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 0, 1, 1, 1)
        self.three = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 2, 2, 1, 1)
        self.one = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 2, 0, 1, 1)
        self.seven = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 0, 0, 1, 1)
        self.two = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 2, 1, 1, 1)
        self.nine = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 0, 2, 1, 1)
        self.six = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 1, 2, 1, 1)
        self.zero = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 3, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 220, 95, 321))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plus = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.plus.setObjectName("plus")
        self.gridLayout_2.addWidget(self.plus, 0, 0, 1, 1)
        self.multiply = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.multiply.setObjectName("multiply")
        self.gridLayout_2.addWidget(self.multiply, 2, 0, 1, 1)
        self.minus = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.minus.setObjectName("minus")
        self.gridLayout_2.addWidget(self.minus, 1, 0, 1, 1)
        self.divide = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.divide.setObjectName("divide")
        self.gridLayout_2.addWidget(self.divide, 3, 0, 1, 1)
        self.backspace = QtWidgets.QPushButton(self.centralwidget)
        self.backspace.setGeometry(QtCore.QRect(210, 170, 93, 41))
        self.backspace.setObjectName("backspace")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(110, 170, 93, 41))
        self.clear.setObjectName("clear")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 170, 93, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 436, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.plus.clicked.connect(self.action_plus)
        self.minus.clicked.connect(self.action_minus)
        self.multiply.clicked.connect(self.action_multiply)
        self.divide.clicked.connect(self.action_divide)
        self.pushButton.clicked.connect(self.action_equal)
        self.backspace.clicked.connect(self.action_delete)
        self.clear.clicked.connect(self.action_clear)
        self.zero.clicked.connect(self.action_zero)
        self.one.clicked.connect(self.action_one)
        self.two.clicked.connect(self.action_two)
        self.three.clicked.connect(self.action_three)
        self.four.clicked.connect(self.action_four)
        self.five.clicked.connect(self.action_five)
        self.six.clicked.connect(self.action_six)
        self.seven.clicked.connect(self.action_seven)
        self.eight.clicked.connect(self.action_eight)
        self.nine.clicked.connect(self.action_nine)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def action_equal(self):
        equation = self.label.text()
        try:
            ans = eval(equation)
            self.label.setText(str(ans))
        except:
            self.label.setText("Wrong Input")

    def action_plus(self):
        text = self.label.text()
        self.label.setText(text + "+")

    def action_minus(self):
        text = self.label.text()
        self.label.setText(text + "-")

    def action_multiply(self):
        text = self.label.text()
        self.label.setText(text + "*")
        
    def action_divide(self):
        text = self.label.text()
        self.label.setText(text + "/")

    def action_one(self):
        text = self.label.text()
        self.label.setText(text + "1")

    def action_two(self):
        text = self.label.text()
        self.label.setText(text + "2")

    def action_three(self):
        text = self.label.text()
        self.label.setText(text + "3")

    def action_four(self):
        text = self.label.text()
        self.label.setText(text + "4")

    def action_five(self):
        text = self.label.text()
        self.label.setText(text + "5")

    def action_six(self):
        text = self.label.text()
        self.label.setText(text + "6")

    def action_seven(self):
        text = self.label.text()
        self.label.setText(text + "7")

    def action_eight(self):
        text = self.label.text()
        self.label.setText(text + "8")

    def action_nine(self):
        text = self.label.text()
        self.label.setText(text + "9")

    def action_zero(self):
        text = self.label.text()
        self.label.setText(text + "0")

    def action_delete(self):
        text = self.label.text()
        print(text[:len(text)-1])
        self.label.setText(text[:len(text)-1])

    def action_clear(self):
        self.label.setText("")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.five.setText(_translate("MainWindow", "5"))
        self.four.setText(_translate("MainWindow", "4"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.three.setText(_translate("MainWindow", "3"))
        self.one.setText(_translate("MainWindow", "1"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.two.setText(_translate("MainWindow", "2"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.six.setText(_translate("MainWindow", "6"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.multiply.setText(_translate("MainWindow", "*"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.backspace.setText(_translate("MainWindow", "Delete"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton.setText(_translate("MainWindow", "Answer"))
        self.label.setText(_translate("MainWindow", "Your Answer Here!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
